[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
conv = "0.3.3"
nanoserde = "0.1.29"
bitfield = "0.13.2"
base64 = "0.13.0"
message-io = "0.14.5"
rand = "0.8.5"
